---
title: "Visualisation discography Ye"
author: "Luka Wong Chung"
date: '2022-02-18'
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(spotifyr)
library(tidyverse)
library(flexdashboard)
```

Column
-----------------------------------------------------------------------
## Introduction
In this repository I work on creating my portfolio for the optional course "Computational Musicology" for my bachelors program "Artificial Intelligence"

The corpus that I chose to use is a Spotify playlist that I made which consists of the entire (released) discography of the American artist Ye, formerly known as Kanye West. I think Ye's discography is particularly interesting for reasearch  because it is very diverse. Throughout the almost 20 years in which Ye has been releasing music, his music has seen many style changes. From his classic debute album "The College Dropout" to his more experimental albums like "Yeezus", Ye has been developing his style throughout the years, which has made him one of the most popular artists of the 21th century. All this makes for great points of comparison. By comparing Ye's music, I hope to find changes in a lot of features that spotify's web API offers. I think throughout the years, Ye's music has gotten more instrumental and I think that there are clear albums that show a change in his music over time, like "808s & Heartbreak" as well as "Yeezus". Something that probably has already been clear from what I've written above, "Yeezus" is an album that stands out a lot in Ye's discography. Tracks like "On Sight" are very experimental and different from most of Ye's tracks. This is probably shown with it having a higher overall energy, as well as having a very different timbre from most songs by being extremely "robotic", by lack of a better word. Another album that stands out in my opinion and is quite innovative is the album "KIDS SEE GHOSTS".

Column
-----------------------------------------------------------------------
## Chart 1
```{r, include=FALSE}
college_dropout <- get_playlist_audio_features("", "2vtt0OdzJ0bug332TuRCOr")
late_regestration <- get_playlist_audio_features("", "2UiJC8DaK3IL2QzJ9yFRKC")
graduation <- get_playlist_audio_features("", "3CjsM5gcnTmX6bnD5HvGzS")
heartbreak <- get_playlist_audio_features("", "2DI1sCSOuSZyVSahhkgL28")
```

```{r, include=FALSE}
first_era <-
  bind_rows(
    college_dropout %>% mutate(category = "The College Dropout"),
    late_regestration %>% mutate(category = "Late Regestration"),
    graduation %>% mutate(category = "Graduation"),
    heartbreak %>% mutate(category = "808s & Heartbreak")
  )
```


```{r, include=FALSE}
first_era %>%
  ggplot(aes(x = speechiness, fill = category)) +
  geom_histogram(binwidth = 0.1, position = "dodge") +
  labs(fill = "Album Name") + ggtitle("Amount of Speechiness Present in Each Song\nof Ye's First Three Studio Albums") +
  theme(plot.title = element_text(lineheight=.8, face="bold"))
```
## Chart 2
```{r, include=FALSE}
ye <- get_artist_audio_features("Kanye west")
```

```{r, include=FALSE}
ye %>%
  ggplot(aes(x = reorder(album_name, order(album_release_year)), y = valence)) +
  stat_summary(fun = mean, geom = "col") +
  theme(axis.text.x = element_blank()) +
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab("Albums") + ggtitle("The Valence of Ye's Albums Ordered from Old to New")
```
## Chart 3
```{r, include=FALSE}
ye %>%
  filter(album_name %in% c("The College Dropout", "808s & Heartbreak", "Yeezus", "The Life Of Pablo")) %>%
  ggplot(aes(loudness, energy, color = album_name)) +
  geom_point(size = 1) + labs(color = "Album Name", y = "Energy", x = "Loudness") +
  ggtitle("Energy of Each Song of Ye's Most Innovative\nAlbums Against its Loudness")
```



